[package]
name = "length-push"
version = "0.1.0"
authors = ["Max Gortman <mgortman@microsoft.com>"]

[dependencies]
tokio-io = "0.1"
tokio-core = "0.1"
net2 = "*"
num_cpus = "1"
native-tls = "*"
clap = "2"
bytes="*"
time="*"
tokio-timer = "*"
error-chain = "*"
futures-await = { git = 'https://github.com/alexcrichton/futures-await' }
uuid = { version = "*", features = ["v4"] }
tokio-tls = { version = "*" }

[profile.release]
debug = true
codegen-units = 1
lto = true
opt-level = 3